In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import seaborn as sns
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import Binarizer

In [2]:
df =sns.load_dataset('titanic')
df_sp = df[['survived','pclass','age','sibsp','parch','fare']].copy()
df_sp.dropna(inplace=True)
df_sp

survived  pclass   age  sibsp  parch     fare
0           0       3  22.0      1      0   7.2500
1           1       1  38.0      1      0  71.2833
2           1       3  26.0      0      0   7.9250
3           1       1  35.0      1      0  53.1000
4           0       3  35.0      0      0   8.0500
..        ...     ...   ...    ...    ...      ...
885         0       3  39.0      0      5  29.1250
886         0       2  27.0      0      0  13.0000
887         1       1  19.0      0      0  30.0000
889         1       1  26.0      0      0  30.0000
890         0       3  32.0      0      0   7.7500

[714 rows x 6 columns]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(df_sp.drop('survived',axis=1), df_sp['survived'], test_size=0.3, random_state=111)

In [4]:
# 평가지표 함수
def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    print('오차 행렬')
    print(confusion)
    print('정확도: {0:.4f}, 정밀도:{1:.4f}, 재현율:{2:.4f}'.format(accuracy, precision, recall))

In [5]:
lr_clf = LogisticRegression(solver='liblinear') 
lr_clf.fit(X_train,y_train)
pred = lr_clf.predict(X_test)
pred

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1], dtype=int64)

In [6]:
get_clf_eval(y_test, pred)

오차 행렬
[[110  25]
 [ 43  37]]
정확도: 0.6837, 정밀도:0.5968, 재현율:0.4625


In [7]:
pred_proba = lr_clf.predict_proba(X_test)
pred_proba

array([[6.74067896e-01, 3.25932104e-01],
       [7.16997795e-01, 2.83002205e-01],
       [5.35951068e-01, 4.64048932e-01],
       [5.90120261e-01, 4.09879739e-01],
       [8.38459049e-01, 1.61540951e-01],
       [2.48198655e-01, 7.51801345e-01],
       [7.84887355e-01, 2.15112645e-01],
       [4.87331285e-01, 5.12668715e-01],
       [3.95401498e-01, 6.04598502e-01],
       [3.36824912e-01, 6.63175088e-01],
       [4.44821607e-01, 5.55178393e-01],
       [8.19371139e-01, 1.80628861e-01],
       [6.65718401e-01, 3.34281599e-01],
       [6.04909944e-01, 3.95090056e-01],
       [6.77010826e-01, 3.22989174e-01],
       [7.32751885e-01, 2.67248115e-01],
       [4.49864818e-01, 5.50135182e-01],
       [3.56780855e-01, 6.43219145e-01],
       [5.76496638e-01, 4.23503362e-01],
       [8.57827854e-01, 1.42172146e-01],
       [6.74980064e-01, 3.25019936e-01],
       [8.82538532e-01, 1.17461468e-01],
       [2.74450283e-01, 7.25549717e-01],
       [7.91675653e-01, 2.08324347e-01],
       [5.894446

In [8]:
X = [[1,0,-1],
    [2,0,0],
    [0,1.3,1.5]]

binarizer = Binarizer(threshold=1.3)
print(binarizer.fit_transform(X))

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [9]:
pred_proba[:,1].reshape(-1,1)

array([[0.3259321 ],
       [0.28300221],
       [0.46404893],
       [0.40987974],
       [0.16154095],
       [0.75180134],
       [0.21511265],
       [0.51266871],
       [0.6045985 ],
       [0.66317509],
       [0.55517839],
       [0.18062886],
       [0.3342816 ],
       [0.39509006],
       [0.32298917],
       [0.26724811],
       [0.55013518],
       [0.64321915],
       [0.42350336],
       [0.14217215],
       [0.32501994],
       [0.11746147],
       [0.72554972],
       [0.20832435],
       [0.41055533],
       [0.17539351],
       [0.35845417],
       [0.49262686],
       [0.86402273],
       [0.86296304],
       [0.38264424],
       [0.28966101],
       [0.33409338],
       [0.55196894],
       [0.08561422],
       [0.22410084],
       [0.56552655],
       [0.32470631],
       [0.50862475],
       [0.33475005],
       [0.79038229],
       [0.23391416],
       [0.49413519],
       [0.64351274],
       [0.54118851],
       [0.47961808],
       [0.23843693],
       [0.975

In [10]:
# 임계값 0.5
tt_threshold = 0.5   
pred_proba_1 = pred_proba[:,1].reshape(-1,1)
binarizer_tt = Binarizer(threshold=tt_threshold).fit(pred_proba_1)
tt_pred = binarizer_tt.transform(pred_proba_1)
get_clf_eval(y_test, tt_pred)

오차 행렬
[[110  25]
 [ 43  37]]
정확도: 0.6837, 정밀도:0.5968, 재현율:0.4625


In [11]:
# 임계값 0.4 
tt_threshold = 0.4 
pred_proba_2 = pred_proba[:,1].reshape(-1,1)
binarizer_tt_1 = Binarizer(threshold=tt_threshold).fit(pred_proba_2)
tt_pred_1 = binarizer_tt_1.transform(pred_proba_2)
get_clf_eval(y_test, tt_pred_1)

오차 행렬
[[94 41]
 [30 50]]
정확도: 0.6698, 정밀도:0.5495, 재현율:0.6250


In [12]:
df_sp.survived.value_counts()

survived
0    424
1    290
Name: count, dtype: int64

In [15]:
thresholds = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

def get_eval_threshold(y_test, pred_proba_1, thresholds):
    for i in thresholds:
        binarizer = Binarizer(threshold=i).fit(pred_proba_1)
        pred = binarizer.transform(pred_proba_1)
        print('\n임계값에 따른 평가지표: 임계값', i)
        get_clf_eval(y_test,pred)
        
get_eval_threshold(y_test,pred_proba[:,1].reshape(-1,1),thresholds)


임계값에 따른 평가지표: 임계값 0.3
오차 행렬
[[69 66]
 [11 69]]
정확도: 0.6419, 정밀도:0.5111, 재현율:0.8625

임계값에 따른 평가지표: 임계값 0.4
오차 행렬
[[94 41]
 [30 50]]
정확도: 0.6698, 정밀도:0.5495, 재현율:0.6250

임계값에 따른 평가지표: 임계값 0.5
오차 행렬
[[110  25]
 [ 43  37]]
정확도: 0.6837, 정밀도:0.5968, 재현율:0.4625

임계값에 따른 평가지표: 임계값 0.6
오차 행렬
[[123  12]
 [ 50  30]]
정확도: 0.7116, 정밀도:0.7143, 재현율:0.3750

임계값에 따른 평가지표: 임계값 0.7
오차 행렬
[[126   9]
 [ 62  18]]
정확도: 0.6698, 정밀도:0.6667, 재현율:0.2250

임계값에 따른 평가지표: 임계값 0.8
오차 행렬
[[129   6]
 [ 67  13]]
정확도: 0.6605, 정밀도:0.6842, 재현율:0.1625
