In [1]:
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

- cross_val_score 
- 교차검증을 사용할 수 있는 여러 방법들 중 하나
- cross_val_score : 교차검증 간단하게 수행할 수 있는 함수
    - k-fold 교차검증을 사용하고, k는 분석가 지정할 수 있다.
    - 클래스의 불균형 상관없이 알아서 잘 확인하고 하니 너무 편하게 사용할 수 있다.
- cross_validate - 교차검증 실행할 수 있음 
    - 여러가지 추가 정보들을 확인할 수 있다. 테스트 훈련시간이나, 테스트 시간 등, 정밀도 재현율, 다른 평가지표 한 번에 볼 수 있음
    - 기능적으로 좀 더 세부적으로 볼 수 있다.

In [3]:
iris= load_iris()
X,y = iris.data, iris.target

In [4]:
clf = RandomForestClassifier(random_state=111)

In [5]:
#cross_val_score 사용해서 교차검증 진행
scores = cross_val_score(clf, X,y, cv=5, scoring='accuracy')

In [6]:
scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [7]:
scores.mean()

0.96

In [8]:
#cross_validate 사용법
scoring=['accuracy','precision','recall','f1']
results= cross_validate(clf, X,y, cv=5, scoring=scoring, return_train_score=True)

C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:842: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 136, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 355, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py", line 2127, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
          

C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:842: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 136, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 355, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yrh07\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py", line 2127, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
          

In [9]:
results

{'fit_time': array([0.06999946, 0.06100011, 0.06000018, 0.06200027, 0.06100035]),
 'score_time': array([0.0129621 , 0.00600004, 0.0059998 , 0.00600004, 0.00499964]),
 'test_accuracy': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ]),
 'train_accuracy': array([1., 1., 1., 1., 1.]),
 'test_precision': array([nan, nan, nan, nan, nan]),
 'train_precision': array([nan, nan, nan, nan, nan]),
 'test_recall': array([nan, nan, nan, nan, nan]),
 'train_recall': array([nan, nan, nan, nan, nan]),
 'test_f1': array([nan, nan, nan, nan, nan]),
 'train_f1': array([nan, nan, nan, nan, nan])}

### 다중분류에서 precision, recall, f1스코어 계산
- macro, micro, weight 사용

In [10]:
scoring=['accuracy','precision_macro','recall_macro','f1_macro']
results_mc= cross_validate(clf, X,y, cv=5, scoring=scoring, return_train_score=True)
results_mc

{'fit_time': array([0.06896496, 0.06050658, 0.05999947, 0.0599997 , 0.06200027]),
 'score_time': array([0.00600028, 0.00600004, 0.00600028, 0.00500011, 0.00499988]),
 'test_accuracy': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ]),
 'train_accuracy': array([1., 1., 1., 1., 1.]),
 'test_precision_macro': array([0.96969697, 0.96969697, 0.94444444, 0.93333333, 1.        ]),
 'train_precision_macro': array([1., 1., 1., 1., 1.]),
 'test_recall_macro': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ]),
 'train_recall_macro': array([1., 1., 1., 1., 1.]),
 'test_f1_macro': array([0.96658312, 0.96658312, 0.93265993, 0.93333333, 1.        ]),
 'train_f1_macro': array([1., 1., 1., 1., 1.])}

In [11]:
scoring=['accuracy','precision_micro','recall_micro','f1_micro']
results_mic= cross_validate(clf, X,y, cv=5, scoring=scoring, return_train_score=True)
results_mic

{'fit_time': array([0.06899858, 0.06199932, 0.06200004, 0.06099963, 0.06100059]),
 'score_time': array([0.00600004, 0.00500083, 0.00599933, 0.00499988, 0.00599933]),
 'test_accuracy': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ]),
 'train_accuracy': array([1., 1., 1., 1., 1.]),
 'test_precision_micro': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ]),
 'train_precision_micro': array([1., 1., 1., 1., 1.]),
 'test_recall_micro': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ]),
 'train_recall_micro': array([1., 1., 1., 1., 1.]),
 'test_f1_micro': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ]),
 'train_f1_micro': array([1., 1., 1., 1., 1.])}

### 이진분류

In [12]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [14]:
df['survived'].value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [15]:
df_tt=df[['survived','pclass','fare','age']]
df_tt=df_tt.dropna()
df_tt_x= df_tt[['pclass','fare','age']]
df_tt_y= df_tt['survived']

cross_val_score(clf, df_tt_x,df_tt_y, cv=5, scoring='accuracy')

array([0.58741259, 0.68531469, 0.63636364, 0.66433566, 0.6971831 ])

In [16]:
scoring=['accuracy','precision','recall','f1']

In [17]:
results= cross_validate(clf, df_tt_x,df_tt_y, cv=5, scoring=scoring, return_train_score=True)
results

{'fit_time': array([0.12000322, 0.1122582 , 0.11100245, 0.10901928, 0.11000204]),
 'score_time': array([0.00900006, 0.00899982, 0.00799966, 0.00898433, 0.00799966]),
 'test_accuracy': array([0.58741259, 0.68531469, 0.63636364, 0.66433566, 0.6971831 ]),
 'train_accuracy': array([0.97022767, 0.98073555, 0.97197898, 0.9737303 , 0.97202797]),
 'test_precision': array([0.49152542, 0.61016949, 0.55555556, 0.6       , 0.64150943]),
 'train_precision': array([0.98206278, 0.97835498, 0.96956522, 0.97379913, 0.97787611]),
 'test_recall': array([0.5       , 0.62068966, 0.51724138, 0.51724138, 0.5862069 ]),
 'train_recall': array([0.94396552, 0.97413793, 0.9612069 , 0.9612069 , 0.95258621]),
 'test_f1': array([0.4957265 , 0.61538462, 0.53571429, 0.55555556, 0.61261261]),
 'train_f1': array([0.96263736, 0.9762419 , 0.96536797, 0.96746204, 0.9650655 ])}

In [18]:
model=[DecisionTreeClassifier(),RandomForestClassifier(),LogisticRegression()]
name = ['DT','RF','LR']

for model, name in zip(model,name):
    print("### 사용할 알고리즘",name,'###')
    for score in ['accuracy','precision','recall','f1']:
        print(score)
        print('-----')
        print(cross_val_score(model,df_tt_x, df_tt_y, scoring=score, cv=5))

### 사용할 알고리즘 DT ###
accuracy
-----
[0.60839161 0.67132867 0.58741259 0.65034965 0.62676056]
precision
-----
[0.54       0.5862069  0.5        0.57692308 0.53030303]
recall
-----
[0.46551724 0.60344828 0.5        0.55172414 0.60344828]
f1
-----
[0.49090909 0.60869565 0.50434783 0.55357143 0.56910569]
### 사용할 알고리즘 RF ###
accuracy
-----
[0.58741259 0.69230769 0.64335664 0.70629371 0.71126761]
precision
-----
[0.5        0.62903226 0.56363636 0.68085106 0.66037736]
recall
-----
[0.51724138 0.62068966 0.53448276 0.56896552 0.5862069 ]
f1
-----
[0.5        0.63865546 0.52252252 0.60952381 0.62385321]
### 사용할 알고리즘 LR ###
accuracy
-----
[0.60839161 0.70629371 0.70629371 0.79020979 0.68309859]
precision
-----
[0.525      0.66       0.7        0.85       0.64444444]
recall
-----
[0.36206897 0.56896552 0.48275862 0.5862069  0.5       ]
f1
-----
[0.42857143 0.61111111 0.57142857 0.69387755 0.5631068 ]
